import { ApiProperty } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsEnum,
  IsInt,
  IsISO8601,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  MaxLength,
  Matches,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { PricingType } from '../../entities/content/product.entity';

export class ProductAssetInputDto {
  @ApiProperty({
    description: 'Publicly accessible URL of the asset',
    example: 'https://cdn.negare.com/assets/product-001/preview-1.png',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(2048)
  url: string;

  @ApiProperty({
    description: 'Optional alternative text for accessibility',
    example: 'Screenshot of the UI kit dashboard page.',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(512)
  alt?: string;

  @ApiProperty({
    description: 'Ordering index to control gallery placement',
    example: 0,
    required: false,
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  order?: number;
}

export class CreateProductDto {
  @ApiProperty({
    description: 'Human readable title for the product',
    example: 'Minimalist UI Kit',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  title: string;

  @ApiProperty({
    description: 'Optional marketing description for the product',
    example: 'A polished set of UI components ready for modern dashboards.',
    required: false,
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({
    description: 'Optional cover image URL for the product card',
    example: 'https://cdn.negare.com/assets/product-001/cover.png',
    required: false,
  })
  @IsOptional()
  @IsUrl()
  coverUrl?: string;

  @ApiProperty({
    description: 'Short unique identifier, autogenerated if omitted',
    example: 'minimalist-ui-kit',
    required: false,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  slug?: string;

  @ApiProperty({
    description: 'Pricing model applied to the product',
    enum: PricingType,
    example: PricingType.FREE,
  })
  @IsEnum(PricingType)
  pricingType: PricingType;

  @ApiProperty({
    description: 'Monetary price stored with two decimal precision',
    example: '29.90',
    required: false,
  })
  @IsOptional()
  @IsString()
  @Matches(/^\d+(\.\d{1,2})?$/, {
    message: 'price must be a numeric string with up to two decimals',
  })
  price?: string;

  @ApiProperty({
    description: 'Flag indicating if the product is visible to customers',
    example: true,
    required: false,
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  active?: boolean;

  @ApiProperty({
    description: 'Optional publication timestamp (ISO 8601)',
    example: '2025-01-30T10:00:00.000Z',
    required: false,
  })
  @IsOptional()
  @IsISO8601()
  publishedAt?: string;

  @ApiProperty({
    description: 'Array of supplier user identifiers that manage the product',
    example: [
      '9e2b4a2c-4c06-4bda-9410-ffb34412dd84',
      '5d07a889-1c9c-4ae3-89e8-2d259e0f9f1c',
    ],
    required: false,
    type: [String],
  })
  @IsOptional()
  @IsArray()
  @IsUUID(undefined, { each: true })
  suppliers?: string[];

  @ApiProperty({
    description: 'Categories to map the product to',
    example: [11, 12],
    required: false,
    type: [Number],
  })
  @IsOptional()
  @IsArray()
  categories?: number[];

  @ApiProperty({
    description: 'Tags associated with the product for quick filtering',
    example: [301, 302],
    required: false,
    type: [Number],
  })
  @IsOptional()
  @IsArray()
  tags?: number[];

  @ApiProperty({
    description: 'Collection of downloadable assets for the product',
    type: [ProductAssetInputDto],
    required: false,
  })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(20)
  @ValidateNested({ each: true })
  @Type(() => ProductAssetInputDto)
  assets?: ProductAssetInputDto[];
}
